import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from "@vercel/analytics/next"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/NavBar";
import Fouter from "@/components/Footer";
import { Spotlight } from "@/components/motion-primitives/spotlight";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
            >
                <div className="relative w-screen sm:h-full min-h-screen rounded-sm border border-primary">

                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                        <Spotlight
                            className='bg-zinc-700 blur-2xl'
                            size={64}
                            springOptions={{
                                bounce: 0.3,
                                duration: 0.1,
                            }}
                        />
                        <NavBar />
                        {children}
                        <Fouter />
                        <Analytics />
                        <SpeedInsights />
                    </ThemeProvider>
                </div>
            </body>
        </html>
    );
}
